export const EVENTS = [
  {
    id: "1",
    name: "Evento - 1",
    description: "Descricao generica do evento1",
    category: "empresa",
    price: 31.0,
    local: "UCB auditório - 1",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
  {
    id: "2",
    name: "Evento - 2",
    description: "Descricao generica do evento2",
    category: "empresa",
    price: 32.0,
    local: "UCB auditório - 2",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "http://auditeste.com.br/wp-content/uploads/2020/01/eventos_ti.jpg",
  },
  {
    id: "3",
    name: "Evento - 3",
    description: "Descricao generica do evento3",
    category: "empresa",
    price: 33.0,
    local: "UCB auditório - 3",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://s2.glbimg.com/O_z6ddxuZ6xA28LMpr1-mPMbDY0=/620x300/e.glbimg.com/og/ed/f/original/2022/01/11/rio-innovation-week-1.jpg",
  },
  {
    id: "4",
    name: "Evento - 4",
    description: "Descricao generica do evento4",
    category: "empresa",
    price: 34.0,
    local: "UCB auditório - 4",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
  {
    id: "5",
    name: "Evento - 5",
    description: "Descricao generica do evento5",
    category: "empresa",
    price: 35.0,
    local: "UCB auditório - 5",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://www.andrecelestino.com/wp-content/uploads/2019/02/db1-calendario-eventos-ti-2019.jpg",
  },
  {
    id: "6",
    name: "Evento - 6",
    description: "Descricao generica do evento6",
    category: "empresa",
    price: 36,
    local: "UCB auditório - 6",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
  {
    id: "7",
    name: "Evento - 7",
    description: "Descricao generica do evento7",
    category: "empresa",
    price: 37,
    local: "UCB auditório - 7",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
  {
    id: "8",
    name: "Evento - 8",
    description: "Descricao generica do evento8",
    category: "empresa",
    price: 38,
    local: "UCB auditório - 8",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
  {
    id: "9",
    name: "Evento - 9",
    description: "Descricao generica do evento9",
    category: "empresa",
    price: 39,
    local: "UCB auditório - 9",
    initalDate: Date.now(),
    finalDate: Date.now(),
    img: "https://blog.even3.com.br/wp-content/uploads/2022/05/17-imagens-de-destaque_guia-de-planejamento-de-eventos.png",
  },
];
